### ISSUE TITLE
Blink to incorect value in Exposure case"Add BNB + ^-8 => Long 11.4"

### ISSUE THREAD

**Issue by TheWilsonGlobal** [derivable-io/derivable-interface#3]
- "To Amt" ^8 sometimes blink to 1.793 smaller than "burn Amt" ^8 then update correct  Amt
- Issue happen after moving slide bar or after timeOut 30s => reEstimate as 1:05s as attached clip

https://user-images.githubusercontent.com/70420596/209464927-440e0f85-26d3-4115-a15a-a5932b653fd9.mp4

**Comment by Zergity** [comment]
please move this issue to `exposure-comp`

**Comment by TheWilsonGlobal** [comment]
This issue already is moved to `exposure-comp` as
https://github.com/derivable-io/exposure-comp/issues/16
