### ISSUE TITLE
[Enhancement] Case Exposure Add LP + ^-8 => Long 6

### ISSUE THREAD

**Issue by TheWilsonGlobal** [derivable-io/derivable-interface#4]
- Actual => Convert total amt of 1.9 LP to ^4, then burn 12.215 ^4 to 16.271 ^8 as 01 img
- Propose => Convert only 1.69 LP to ^4, the rest 0.21 LP will be converted to 16.271 ^8  directly to save burn  transaction and optimize gas

![image](https://user-images.githubusercontent.com/70420596/209465130-2cc927e7-cb65-4d16-8ae5-318f77d64032.png)

**Comment by Zergity** [comment]
this should be in `power-lib`, but it's expected since tx from/to C-token would be the most expensive one

**Comment by TheWilsonGlobal** [comment]
This issue already moved to ` power-lib` as

https://github.com/derivable-io/power-lib/issues/4
